# Change these first
owner: bodysano # Your GitHub organization or username, where this repository lives
repo: bodysano-status # The name of this repository

sites:
  - name: BodySano Website
    url: https://www.bodysano.com
  - name: BodyDiet
    url: https://diet.bodysano.com
  - name: BodySano API
    url: https://api.bodysano.com

status-website:
  baseUrl: /bodysano-status
  name: BodySano
  navbar:
    - title: Status
      href: /
